[workspace]
members = ["projects/*"]
default-members = [
    "projects/pi-search",
    "projects/pi-search-demo",
]

exclude = [
    "projects/y-cruncher",
    "projects/.DS_Store",
]

[profile.release]
lto = true
