[package]
name = "demo"
version = "1.0.0"
publish = false
readme = "readme.md"
edition = "2021"


[dependencies]
log = "0.4.14"
wasm-logger = "0.2.0"
dioxus = { version = "0.2.3", features = ["web"] }
pi-search = { path = "../pi-search"}
